name: Create empty branch
on: workflow_dispatch
jobs:
  create-empty-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create and push empty branch
        run: |
          git checkout --orphan empty-branch
          git rm -rf .
          echo "# Empty branch" > README.md
          git add README.md
          git commit -m "Initial commit (empty branch)"
          git push origin empty-branch
